[package]
name = "burqshare"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = {"version" = "1.0.219", features = ["derive"]}
serde_json = "1.0.140"
tokio ={ "version"="1", features = ["full"]}
uuid = { "version" = "1.16.0", features = ["v4", "serde"]}
